version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: your_strong_postgres_password
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: your_strong_pgadmin_password
    restart: unless-stopped

  mongo:
    container_name: container-mongo
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: your_strong_mongo_password
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:  
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  mongo-data: